# Generated by Django 5.2.17 on 2026-08-31 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('threshold_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('trend_window_days', models.PositiveIntegerField(default=1)),
                ('severity', models.CharField(choices=[('information', 'Information'), ('attention', 'Attention'), ('preoccupant', 'Préoccupant'), ('critique', 'Critique')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alert_rules',
            },
        ),
        migrations.CreateModel(
            name='HealthAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('risk_level', models.CharField(choices=[('information', 'Information'), ('attention', 'Attention'), ('preoccupant', 'Préoccupant'), ('critique', 'Critique')], default='information', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('confidence', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('explanation', models.TextField(blank=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_analyses', to='flocks.flock')),
            ],
            options={
                'db_table': 'health_analyses',
                'indexes': [models.Index(fields=['flock', 'run_at'], name='health_anal_flock_i_d87944_idx')],
            },
        ),
    ]
