# Generated by Django 5.2.17 on 2026-08-31 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('information', 'Information'), ('attention', 'Attention'), ('preoccupant', 'Préoccupant'), ('critique', 'Critique')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('acknowledged', 'Acquitté'), ('closed', 'Clos')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='flocks.flock')),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
    ]
