# Generated by Django 5.2.17 on 2026-08-31 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='health_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_alerts', to='health.healthanalysis'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['flock', 'status'], name='alerts_flock_i_3962ca_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['flock', 'rule_code', 'created_at'], name='alerts_flock_i_1b985e_idx'),
        ),
    ]
