# Generated by Django 6.0.8 on 2026-08-30 19:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('dead_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('presumed_cause', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('client_uuid', models.UUIDField(unique=True)),
                ('sync_status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalities', to='flocks.flock')),
            ],
            options={
                'db_table': 'mortalities',
                'indexes': [models.Index(fields=['flock', 'date'], name='mortalities_flock_i_92e95d_idx')],
            },
        ),
    ]
