# Generated by Django 6.0.8 on 2026-08-30 19:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Mâle'), ('female', 'Femelle'), ('mixed', 'Mixte')], default='mixed', max_length=10)),
                ('initial_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_count', models.PositiveIntegerField()),
                ('arrival_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('closed', 'Clôturé')], default='active', max_length=10)),
                ('client_uuid', models.UUIDField(unique=True)),
                ('sync_status', models.CharField(default='synced', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flocks', to='farms.farm')),
            ],
            options={
                'db_table': 'flocks',
                'indexes': [models.Index(fields=['farm', 'status'], name='flocks_farm_id_ec3324_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('current_count__lte', models.F('initial_count'))), name='flock_current_count_lte_initial'), models.UniqueConstraint(fields=('farm', 'reference'), name='unique_flock_reference_per_farm')],
            },
        ),
    ]
