# Generated by Django 5.2.17 on 2026-08-31 22:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMonitoring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('water_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('feed_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('average_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('client_uuid', models.UUIDField(unique=True)),
                ('sync_status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_monitorings', to='flocks.flock')),
            ],
            options={
                'db_table': 'daily_monitorings',
                'indexes': [models.Index(fields=['flock', 'date'], name='daily_monit_flock_i_b5542e_idx')],
            },
        ),
    ]
