# Generated by Django 5.2.17 on 2026-08-31 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SynchronizationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('partial', 'Partiel (avec erreurs)'), ('failed', 'Échec')], default='failed', max_length=15)),
                ('pull_count', models.PositiveIntegerField(default=0)),
                ('push_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'synchronization_logs',
                'indexes': [models.Index(fields=['user', 'started_at'], name='synchroniza_user_id_452147_idx')],
            },
        ),
    ]
