# Generated by Django 5.2.17 on 2026-08-31 22:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('abnormal_behavior', 'Comportement anormal'), ('respiratory', 'Respiratoire'), ('feeding', 'Alimentation'), ('digestive', 'Digestif'), ('plumage', 'Plumage'), ('locomotor', 'Locomoteur'), ('other', 'Autre')], max_length=25)),
                ('description', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('client_uuid', models.UUIDField(unique=True)),
                ('sync_status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='flocks.flock')),
            ],
            options={
                'db_table': 'observations',
                'indexes': [models.Index(fields=['flock', 'date'], name='observation_flock_i_7f55b1_idx')],
            },
        ),
    ]
