# Generated by Django 5.2.17 on 2026-09-01 21:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('client_uuid', models.UUIDField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_schedules', to='flocks.flock')),
            ],
            options={
                'db_table': 'health_schedules',
                'ordering': ['scheduled_date'],
                'indexes': [models.Index(fields=['flock', 'scheduled_date'], name='health_sche_flock_i_c1f6f7_idx')],
            },
        ),
    ]
